apiVersion: v1
kind: Service
metadata:
  name: flash-app-service
  namespace: flash
spec:
  selector:
    app: flash-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer