apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: authorizationpolicies.security.istio.io
  labels:
    istio: security
    release: istio
spec:
  group: security.istio.io
  scope: Namespaced
  names:
    kind: AuthorizationPolicy
    listKind: AuthorizationPolicyList
    plural: authorizationpolicies
    singular: authorizationpolicy
    shortNames:
    - ap
  # Defines the versions of this CRD that are served
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: "Defines the specification for an AuthorizationPolicy."
              #
              # SIMPLIFIED SCHEMA
              properties:
                action:
                  type: string
                  enum: ["ALLOW", "DENY", "AUDIT", "CUSTOM"]
                rules:
                  type: array
                  items:
                    type: object
                selector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
            status:
              type: object
      additionalPrinterColumns:
        - name: Action
          type: string
          jsonPath: .spec.action
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp