apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#- asm-policy-v0.0.1	# ASM not installed on cluster
- cis-gke-v1.5.0
- cis-k8s-v1.5.1
#- cis-k8s-v1.7.1  # potential new version
#- cost-reliability-v2023
#- mitre-v2024
- nist-sp-800-53-r5
#- nsa-cisa-k8s-v1.2
#- pci-dss-v3.2.1
#- pci-dss-v3.2.1-extended
#- pci-dss-v4.0
#- policy-essentials-v2022
#- psp-v2022
#- pss-baseline-v2022
#- pss-restricted-v2022
#- nist-sp-800-190
