apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- allowedserviceportname.yaml
- asmauthzpolicydefaultdeny.yaml
- asmauthzpolicydisallowedprefix.yaml
- asmauthzpolicyenforcesourceprincipals.yaml
- asmauthzpolicynormalization.yaml
- asmauthzpolicysafepattern.yaml
- asmingressgatewaylabel.yaml
- asmpeerauthnmeshstrictmtls.yaml
- asmpeerauthnstrictmtls.yaml
- asmrequestauthnprohibitedoutputheaders.yaml
- asmsidecarinjection.yaml
- destinationruletlsenabled.yaml
- disallowedauthzprefix.yaml
- gcpstoragelocationconstraintv1.yaml
- gkespotvmterminationgrace.yaml
- k8sallowedrepos.yaml
- k8savoiduseofsystemmastersgroup.yaml
- k8sblockallingress.yaml
- k8sblockcreationwithdefaultserviceaccount.yaml
- k8sblockendpointeditdefaultrole.yaml
- k8sblockloadbalancer.yaml
- k8sblocknodeport.yaml
- k8sblockobjectsoftype.yaml
- k8sblockprocessnamespacesharing.yaml
- k8sblockwildcardingress.yaml
- k8scontainerephemeralstoragelimit.yaml
- k8scontainerlimits.yaml
- k8scontainerratios.yaml
- k8scontainerrequests.yaml
- k8scronjoballowedrepos.yaml
- k8sdisallowanonymous.yaml
- k8sdisallowedrepos.yaml
- k8sdisallowedrolebindingsubjects.yaml
- k8sdisallowedtags.yaml
- k8sdisallowinteractivetty.yaml
- k8semptydirhassizelimit.yaml
- k8senforcecloudarmorbackendconfig.yaml
- k8senforceconfigmanagement.yaml
- k8sexternalips.yaml
- k8shorizontalpodautoscaler.yaml
- k8shttpsonly.yaml
- k8simagedigests.yaml
- k8slocalstoragerequiresafetoevict.yaml
- k8smemoryrequestequalslimit.yaml
- k8snoenvvarsecrets.yaml
- k8snoexternalservices.yaml
- k8spoddisruptionbudget.yaml
- k8spodresourcesbestpractices.yaml
- k8spodsrequiresecuritycontext.yaml
- k8sprohibitrolewildcardaccess.yaml
- k8spspallowedusers.yaml
- k8spspallowprivilegeescalationcontainer.yaml
- k8spspapparmor.yaml
- k8spspautomountserviceaccounttokenpod.yaml
- k8spspcapabilities.yaml
- k8spspflexvolumes.yaml
- k8spspforbiddensysctls.yaml
- k8spspfsgroup.yaml
- k8spsphostfilesystem.yaml
- k8spsphostnamespace.yaml
- k8spsphostnetworkingports.yaml
- k8spspprivilegedcontainer.yaml
- k8spspprocmount.yaml
- k8spspreadonlyrootfilesystem.yaml
- k8spspseccomp.yaml
- k8spspselinuxv2.yaml
- k8spspvolumetypes.yaml
- k8spspwindowshostprocess.yaml
- k8spssrunasnonroot.yaml
- k8sreplicalimits.yaml
- k8srequireadmissioncontroller.yaml
- k8srequirebinauthz.yaml
- k8srequirecosnodeimage.yaml
#- k8srequiredaemonsets.yaml - use the custom SE version
- k8srequiredannotations.yaml
- k8srequiredefaultdenyegresspolicy.yaml
- k8srequiredlabels.yaml
- k8srequiredprobes.yaml
- k8srequiredresources.yaml
- k8srequirenamespacenetworkpolicies.yaml
- k8srequirevalidrangesfornetworks.yaml
- k8srestrictadmissioncontroller.yaml
- k8srestrictautomountserviceaccounttokens.yaml
- k8srestrictlabels.yaml
- k8srestrictnamespaces.yaml
- k8srestrictnfsurls.yaml
- k8srestrictrbacsubjects.yaml
- k8srestrictrolebindings.yaml
- k8srestrictrolerules.yaml
- k8sstorageclass.yaml
- k8suniqueingresshost.yaml
- k8suniqueserviceselector.yaml
- noupdateserviceaccount.yaml
- policystrictonly.yaml
- restrictnetworkexclusions.yaml
- sourcenotallauthz.yaml
- verifydeprecatedapi.yaml