# Copyright 2024 Google LLC
#
# This is “Software” that is licensed under the “General Software” section of
# the Service Specific Terms (https://cloud.google.com/terms/service-terms) for
# usage in accordance with the following “Scope of Use”: This file may only be
# used on an Anthos cluster, including any associated ci/cd use. “Anthos
# cluster” is defined as “A Cluster (of any kind) registered to a fleet project
# where the Anthos API is enabled”.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- se-5.1.3_prohibit-role-wildcard-access.yaml
- se-5.2.5_psp-allow-privilege-escalation-container.yaml
- se-5.2.1_psp-privileged-container.yaml
- se-5.3.2_require-namespace-network-policies.yaml